// Code generated by ifacemaker; DO NOT EDIT.

package storage

import (
	"github.com/katalabut/money-tell-api/internal/entities"
)

// Storage ...
type Storage interface {
	GetPays() ([]entities.Pay, error)
	AddPay(title string, price float32) entities.Pay
}
