//go:generate ifacemaker -f storage.go -f pay.go -s StorageImpl -p storage -i Storage -o interface.go --doc=false -c "Code generated by ifacemaker; DO NOT EDIT."

package storage

type StorageImpl struct {
}

func New() *StorageImpl {
	return &StorageImpl{}
}
