// Code generated by ifacemaker; DO NOT EDIT.

package storage

import (
	"context"

	"github.com/katalabut/money-tell-api/app/entities"
)

// Storage ...
type Storage interface {
	GetPays(ctx context.Context) ([]*entities.PayDate, error)
	AddPay(title string, price float32) (*entities.Pay, error)
	FindUser(ctx context.Context, email, pass string) (*entities.User, error)
	FindUserByID(ctx context.Context, hex string) (*entities.User, error)
	InsertUser(ctx context.Context, email, pass string) (*entities.User, error)
}
