//go:generate ifacemaker -f storage.go -f pay.go -s StorageImpl -p storage -i Storage -o interface.go --doc=false -c "Code generated by ifacemaker; DO NOT EDIT."

package storage

import (
	"go.mongodb.org/mongo-driver/mongo"
)

type StorageImpl struct {
	users, pays *mongo.Collection
}

func New(db *mongo.Database) *StorageImpl {
	return &StorageImpl{
		users: db.Collection("users"),
		pays:  db.Collection("pays"),
	}
}
